Issue 30 uri schema
emc-mongoose/mongoose-storage-driver-pravega pull request #11
Opened 2018-10-23 18:58 UTC by zhenytim

2018-10-24 06:51 UTC, akurilov requested changes

2018-10-24 06:51 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriverExtension.java
> -				Constants.DEFAULT_CONTROLLER_URI, stepId, dataInput, storageConfig, verifyFlag, batchSize
the URI schema value should be under the "storageConfig" structure with the relative path "net-uri-schema", no additional argument is needed

2018-10-24 06:51 UTC, akurilov commented on src/main/resources/config-schema-storage-net.json
> +			"storage-net-uri-schema":"string",
the option is already inside the "storage" and "net" blocks, should be instead:
```
            "uri" : {
                "schema": "string"
            }
```

2018-10-24 06:51 UTC, akurilov commented on src/main/resources/config/defaults-storage-net.json
> +			"storage-net-uri-schema": "tcp",
the option is already inside the "storage" and "net" blocks, should be instead:
```
            "uri": {
                "schema": "tcp"
            }
```

2018-10-24 06:51 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
>  		this.uriSchema = uriSchema;
should be:
```
this.uriSchema = storageConfig.stringVal("net-uri-schema");
```

2018-10-27 14:38 UTC, akurilov requested changes

2018-10-27 14:38 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriverExtension.java
> +	private final String uriSchema()  {
`SCHEMA_PROVIDER` is a configuration validation schema. This doesn't relate to the URI schema. I don't think that this method is needed

2018-10-29 10:35 UTC, veronikaKochugova approved these changes

2018-10-31 16:13 UTC, akurilov approved these changes

2018-10-31 18:29 UTC, veronikaKochugova commented
Please resolve the conflict

2018-11-06 07:08 UTC, veronikaKochugova requested changes
Please resolve the conflict

2018-11-09 11:15 UTC, zhenytim commented
tests fail because of missing parts of code from other new branches.
compilation without errors.

2018-11-29 22:47 UTC, zhenytim commented
Difficult to resolve conflicts after adoption, issue solved in another branch

2018-11-29 22:47 UTC, closed without merging