Issue 50 read event adoption
emc-mongoose/mongoose-storage-driver-pravega pull request #25
Opened 2018-11-16 11:03 UTC by zhenytim

2018-11-16 21:01 UTC, akurilov requested changes

2018-11-16 21:01 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +		@Cleanup val clientFactory = ClientFactory.withScope(scopeName, controllerURI);
The client factory should be obtained from the cache

2018-11-16 21:01 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +		@Cleanup val readerGroupManager = ReaderGroupManager.withScope(scopeName, controllerURI);
this should be cached in the same way as the client factories

2018-11-16 21:01 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +		@Cleanup val reader = clientFactory.createReader("reader",
should be cached

2018-11-16 21:01 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +				new JavaSerializer<String>(),
ByteBuffer serializer should be used

2018-11-16 21:01 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +				if (event.getEvent() != null) {
the condition is already passed in the loop statement
2nd invocation will have no effect

2018-11-16 21:01 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +					System.out.format("Read event '%s'%n", event.getEvent());
Let's replace this w/ `Loggers.MSG.trace(...)` call

2018-11-16 21:01 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +import io.pravega.client.stream.*;
we should not use the wildcard import statements, please fix it

2018-11-16 21:01 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +		extends CoopStorageDriverBase<I, O> {
Please rollback all autoformatting related changes. These changes pollute the diff

2018-11-20 12:46 UTC, dadlex commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +		val scopeName = path.substring(0, path.indexOf("/"));
If I remember correctly, we don't store scope in the operation anymore

2018-11-20 12:47 UTC, dadlex commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +		System.out.format("No more events from %s/%s%n", scopeName, streamName);
"Let's replace this w/ Loggers.MSG.trace(...) call" as Andrey says. I think it should be applied here as well

2018-11-22 19:24 UTC, dadlex commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +	private final Map<ClientFactory, ReaderCreateFunction> eventStreamReaderCreateFunctionMapCache = new ConcurrentHashMap<>();
the word map seems excessive

2018-11-22 19:25 UTC, dadlex commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +		val streamName = path.substring(path.indexOf("/") + 1);
Andrey wrote a nice peace of code in eventCreate method on extracting a right streamName

2018-11-22 19:27 UTC, dadlex commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +		}
I think you forgot to call all the completion methods. Look at eventCreate for an example

2018-11-22 19:30 UTC, dadlex commented on src/main/java/com/emc/mongoose/storage/driver/pravega/cache/ReaderCreateFunctionImpl.java
> +		return clientFactory.createReader("reader", readerGroup, new DataItemSerializer(true), ReaderConfig.builder().build());
Dont we have an DataItemSerializer as a class field? evtSerializer i guess?

2018-11-22 20:25 UTC, dadlex commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +			for (event = reader.readNextEvent(readTimeoutMillis); null != event.getEvent(); ) {
I'm totally lost now. @akurilov  For now the only difference between eventRead and streamRead is how we get the metrics? So the difference will be in completeEventRead vs completeStreamRead?

2018-11-23 19:26 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/cache/ReaderCreateFunctionImpl.java
> +		return clientFactory.createReader("reader", readerGroup, new DataItemSerializer(true), ReaderConfig.builder().build());
I guess we should use some kind of the ByteBuffer [de]serializer. Because the DataItemSerializer cannot deserialize. Also, we have a working example in the tests.

2018-11-23 19:27 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/PravegaStorageDriver.java
> +			for (event = reader.readNextEvent(readTimeoutMillis); null != event.getEvent(); ) {
Probably yes but I'm not sure

2018-11-30 13:01 UTC, akurilov approved these changes

2018-12-02 13:35 UTC, merged