Add test for CreateEvent
emc-mongoose/mongoose-storage-driver-pravega pull request #27
Opened 2018-11-20 11:15 UTC by dadlex

Add test to check that event is created.
Also change composition back to inheritance. At least until we decide to change pravegaStorageDriver methods' types.

The only question left: how to get size of the stream to check that its size == dataItem.size(). Until that we only check operation status and equality of dataItem and created task.

2018-11-20 13:43 UTC, akurilov approved these changes

2018-11-30 11:51 UTC, dadlex commented
Pay attention to ByteBufferSerializer. I'm not sure it's doing what we want. But that's what I understood from our conversation.

2018-11-30 12:57 UTC, akurilov requested changes

2018-11-30 12:57 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/io/ByteBufferSerializer.java
> +implements Serializer<Integer>, Serializable {
Looks to be a kind of bad idea. Let's use a deserializer which just returns the received byte buffer. Then we should just estimate the byte count in the buffer and forget it.

2018-11-30 12:57 UTC, akurilov commented on src/main/java/com/emc/mongoose/storage/driver/pravega/io/ByteBufferSerializer.java
> +		int bytesDone = 0;
It should be just
`final int bytesDone = serializedValue.remaining();`
instead of loop

2018-12-07 12:03 UTC, akurilov approved these changes

2018-12-08 17:35 UTC, merged